'use client';

import Link from 'next/link';
import { useLanguage } from '@/lib/i18n/context';
import styles from '../legal.module.css';

const content = {
  en: {
    title: 'Terms of Service',
    badge: 'Legal',
    updated: 'Last updated: June 14, 2026',
    back: '← Back to WebWeave',
    sections: [
      {
        title: '1. About the Service',
        paragraphs: [
          'WebWeave is an AI-powered service that helps create automation scripts for website testing. You enter a target URL and objective, and WebWeave analyzes the page and generates automation code using frameworks like Playwright, Puppeteer, Selenium, or Cypress.',
          'By using WebWeave, you agree to comply with these terms and conditions.',
        ],
      },
      {
        title: '2. Permitted Use',
        body: 'You may use WebWeave to:',
        list: [
          'Create automation scripts for QA testing of websites you own or have permission to test.',
          'Learn automation and explore testing frameworks.',
          'Create starter scripts for your professional projects.',
        ],
      },
      {
        title: '3. Prohibited Use',
        body: 'You <strong>may not</strong> use WebWeave to:',
        list: [
          'Scrape websites without the website owner\'s permission.',
          'Create bots to bypass CAPTCHA, perform credential stuffing, or automated attacks.',
          'Access or collect other people\'s personal data without permission.',
          'Conduct illegal activities, including hacking, phishing, or malware distribution.',
          'Attempt to exploit WebWeave\'s or its infrastructure\'s vulnerabilities.',
          'Abuse quotas or create multiple accounts to bypass usage limits.',
        ],
        paragraphs: [
          'Violations may result in account suspension or deletion without refund.',
        ],
      },
      {
        title: '4. Account and Security',
        list: [
          'You are responsible for maintaining the security of your account and password.',
          'One person may only have one active account.',
          'Do not enter real credentials (production username/password) into prompts. Use placeholders.',
          'Immediately report any unauthorized account usage to us.',
        ],
      },
      {
        title: '5. Plans and Payments',
        list: [
          'WebWeave offers Free, Starter, and Pro plans with different generation limits.',
          'Payments are processed through Midtrans. Prices are in Indonesian Rupiah (IDR).',
          'Paid plans are valid for 30 days (monthly) or 365 days (annual) from the payment date.',
          'Generation quotas do not carry over to the next month.',
          'After the period ends, your account will revert to the Free plan if not renewed.',
        ],
      },
      {
        title: '6. Refund Policy',
        body: 'As WebWeave is a digital service that activates immediately upon payment, refunds are only provided under the following conditions:',
        list: [
          'Double charge — full refund for duplicate payments.',
          'Service inaccessible for more than 72 consecutive hours due to our error — prorated refund.',
        ],
        paragraphs: [
          'Refund requests must be submitted within 14 days of payment via email to our support.',
        ],
      },
      {
        title: '7. Generated Code',
        list: [
          'Scripts generated by WebWeave belong to you. You are free to use, modify, and distribute them.',
          'WebWeave does not guarantee that generated scripts will run perfectly without modification. Scripts are starter code that may need adjustments.',
          'WebWeave is not responsible for any damage or issues caused by the use of generated scripts.',
        ],
      },
      {
        title: '8. Limitation of Liability',
        body: 'WebWeave is provided "as-is". We do not guarantee:',
        list: [
          'That the service will always be available without interruption.',
          'That generated scripts will work 100% correctly on all websites.',
          'That generation results will meet your expectations in every case.',
        ],
        paragraphs: [
          'Our maximum liability is limited to the amount you paid in the last 30 days.',
        ],
      },
      {
        title: '9. Service Changes',
        body: 'We may change WebWeave\'s features, pricing, or usage limits at any time. Price changes apply to the next billing period, not the current one. Significant changes will be communicated at least 7 days in advance via email.',
      },
      {
        title: '10. Governing Law',
        body: 'These terms are governed by the laws of the Republic of Indonesia. Any disputes will be resolved through deliberation first before proceeding through legal channels in the competent courts of Indonesia.',
      },
    ],
    contact: 'Questions about the terms? Contact us at',
    email: 'support@webweave.app',
  },
  id: {
    title: 'Syarat & Ketentuan',
    badge: 'Legal',
    updated: 'Terakhir diperbarui: 14 Juni 2026',
    back: '← Kembali ke WebWeave',
    sections: [
      {
        title: '1. Tentang Layanan',
        paragraphs: [
          'WebWeave adalah layanan AI-powered yang membantu membuat script automation untuk testing website. Kamu memasukkan URL target dan objective, lalu WebWeave menganalisis halaman dan menghasilkan kode automation menggunakan framework seperti Playwright, Puppeteer, Selenium, atau Cypress.',
          'Dengan menggunakan WebWeave, kamu setuju untuk mematuhi syarat dan ketentuan ini.',
        ],
      },
      {
        title: '2. Penggunaan yang Diperbolehkan',
        body: 'Kamu boleh menggunakan WebWeave untuk:',
        list: [
          'Membuat script automation untuk QA testing website milik kamu atau yang kamu punya izin untuk test.',
          'Belajar automation dan eksplorasi framework testing.',
          'Membuat starter script untuk project profesional kamu.',
        ],
      },
      {
        title: '3. Penggunaan yang Dilarang',
        body: 'Kamu <strong>tidak boleh</strong> menggunakan WebWeave untuk:',
        list: [
          'Scraping website tanpa izin pemilik website.',
          'Membuat bot untuk bypass CAPTCHA, credential stuffing, atau serangan otomatis.',
          'Mengakses atau mengumpulkan data pribadi orang lain tanpa izin.',
          'Aktivitas ilegal, termasuk hacking, phishing, atau distribusi malware.',
          'Mencoba mengeksploitasi kerentanan WebWeave atau infrastrukturnya.',
          'Menyalahgunakan quota atau membuat akun ganda untuk menghindari batas penggunaan.',
        ],
        paragraphs: [
          'Pelanggaran dapat mengakibatkan penangguhan atau penghapusan akun tanpa refund.',
        ],
      },
      {
        title: '4. Akun dan Keamanan',
        list: [
          'Kamu bertanggung jawab menjaga keamanan akun dan password kamu.',
          'Satu orang hanya boleh memiliki satu akun aktif.',
          'Jangan masukkan kredensial asli (username/password production) ke dalam prompt. Gunakan placeholder.',
          'Segera laporkan ke kami jika ada penggunaan akun yang tidak sah.',
        ],
      },
      {
        title: '5. Paket dan Pembayaran',
        list: [
          'WebWeave menyediakan paket Free, Starter, dan Pro dengan batas generation berbeda.',
          'Pembayaran diproses melalui Midtrans. Harga dalam Rupiah Indonesia (IDR).',
          'Paket berbayar berlaku untuk periode 30 hari (bulanan) atau 365 hari (tahunan) dari tanggal pembayaran.',
          'Quota generation tidak dapat dipindahkan ke bulan berikutnya.',
          'Setelah periode berakhir, akun akan kembali ke paket Free jika tidak diperpanjang.',
        ],
      },
      {
        title: '6. Kebijakan Refund',
        body: 'Karena layanan WebWeave adalah layanan digital yang langsung aktif setelah pembayaran, refund hanya diberikan dalam kondisi berikut:',
        list: [
          'Pembayaran ganda (double charge) — refund penuh untuk pembayaran duplikat.',
          'Layanan tidak bisa diakses selama lebih dari 72 jam berturut-turut karena kesalahan kami — refund prorata.',
        ],
        paragraphs: [
          'Permintaan refund harus diajukan dalam 14 hari setelah pembayaran melalui email ke support kami.',
        ],
      },
      {
        title: '7. Kode yang Di-generate',
        list: [
          'Script yang di-generate oleh WebWeave adalah milik kamu. Kamu bebas menggunakan, memodifikasi, dan mendistribusikannya.',
          'WebWeave tidak menjamin bahwa script yang di-generate akan berjalan sempurna tanpa modifikasi. Script adalah starter code yang mungkin perlu penyesuaian.',
          'WebWeave tidak bertanggung jawab atas kerusakan atau masalah yang ditimbulkan oleh penggunaan script yang di-generate.',
        ],
      },
      {
        title: '8. Batasan Tanggung Jawab',
        body: 'WebWeave disediakan "sebagaimana adanya" (as-is). Kami tidak menjamin:',
        list: [
          'Layanan akan selalu tersedia tanpa gangguan.',
          'Script yang di-generate akan berjalan 100% benar di semua website.',
          'Hasil generation akan sesuai dengan ekspektasi kamu di setiap kasus.',
        ],
        paragraphs: [
          'Tanggung jawab maksimal kami terbatas pada jumlah yang kamu bayarkan dalam 30 hari terakhir.',
        ],
      },
      {
        title: '9. Perubahan Layanan',
        body: 'Kami dapat mengubah fitur, harga, atau batas penggunaan WebWeave sewaktu-waktu. Perubahan harga berlaku untuk periode billing berikutnya, bukan periode yang sedang berjalan. Perubahan signifikan akan diinformasikan minimal 7 hari sebelumnya melalui email.',
      },
      {
        title: '10. Hukum yang Berlaku',
        body: 'Syarat dan ketentuan ini tunduk pada hukum Republik Indonesia. Segala sengketa akan diselesaikan melalui musyawarah terlebih dahulu sebelum melalui jalur hukum di pengadilan yang berwenang di Indonesia.',
      },
    ],
    contact: 'Pertanyaan tentang syarat dan ketentuan? Hubungi kami di',
    email: 'support@webweave.app',
  },
};

export default function TermsOfService() {
  const { lang } = useLanguage();
  const c = content[lang] || content.en;

  return (
    <div className={styles.legalPage}>
      <Link href="/" className={styles.backLink}>{c.back}</Link>
      <div className={styles.badge}>{c.badge}</div>
      <h1 className={styles.title}>{c.title}</h1>
      <p className={styles.lastUpdated}>{c.updated}</p>

      {c.sections.map((section, i) => (
        <section key={i} className={styles.section}>
          <h2 className={styles.sectionTitle}>{section.title}</h2>
          {section.paragraphs && section.paragraphs.map((p, j) => (
            <p key={j} className={styles.paragraph}>{p}</p>
          ))}
          {section.body && <p className={styles.paragraph} dangerouslySetInnerHTML={{ __html: section.body }} />}
          {section.list && (
            <ul className={styles.list}>
              {section.list.map((item, j) => (
                <li key={j}>{item}</li>
              ))}
            </ul>
          )}
        </section>
      ))}

      <div className={styles.divider} />
      <div className={styles.contactBox}>
        <p>
          {c.contact}{' '}
          <a href={`mailto:${c.email}`}>{c.email}</a>
        </p>
      </div>
    </div>
  );
}
